### PR TITLE
Add level progress bar to char profiles

### PR DESCRIPTION
**Pull request by jkisor**
Issue https://github.com/amoeba/treestats.net/issues/101

### References:

- `EXPERIENCE_BY_LEVEL` values: [here](https://asheron.fandom.com/wiki/Experience_Points)
- Progress bar styling: [here](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient()#gradient_with_multi-position_color_stops)

### Small Progress Example:
treestats_small_progress

### Large Progress Example:
treestats_large_progress

### Max Level Example:
treestats_max_level

### CODE REVIEW

**Comment by jkisor** [comment]
Hello @amoeba, I'm a fan of Asheron's Call (and Treestats, of course) as well as a Ruby developer. Hope you don't mind me dropping in to contribute.

I tried my best to stick to the style/patterns already present. Happy to make adjustments at your direction, let me know. Thanks!

**Comment by amoeba** [comment]
Heya @jkisor, I do not mind you dropping in to contribute _at all_. Thanks for taking the time to contribute.

Your changes look great. I noticed one bug where your code wouldn't handle some of the characters on custom servers who allow characters above level 275 (like InfiniteAC), so I've tweaked that part in f967cbd44f7524237b25f3d0fa3963b6c5c4a605. It's a pretty reasonable thing not to account for -- I didn't for quite a while until recently.

I also thought it might look neater if it looked like how it does ingame,

Screen Shot 2021-10-16 at 10 29 32 AM

So I fiddled around and tweaked your code to make it look like:

Screen Shot 2021-10-16 at 10 30 12 PM

I hope that's okay.

Again, thank you so much for contributing this. And extra thanks for the details in your PR and also for including tests.

This repo is a mirror of the private repo I use to manage the full source in order to hide some of the workings of the client->server encryption I use so I have to close this PR as _unmerged_ but I've preserved your commits so you'll get credit just the same. Thanks again.

**Comment by amoeba** [comment]
Closed as unmerged since this is a mirror but commits in this PR retained as in:

- https://github.com/amoeba/treestats.net/commit/308668a3ca572b673e70790926b90cc9dbb3fffb
- https://github.com/amoeba/treestats.net/commit/fed857458f132351cc2df5ee709f9aff5d1eaabd

**Comment by amoeba** [comment]
Changes and my tweaks are now live on treestats.net.

**Comment by jkisor** [comment]
Well done! It looks great. 🎉

**Pull request closed without merging**
